-- mart_a1_06_may24_churn_risk: scores mart_a1_05_may24_population (D-08 population)
-- with the trained logistic regression from work/WP20_cohorts_churn/churn_model.py.
-- AUTO-GENERATED by churn_model.py -- do not hand-edit; re-run the script to refresh the
-- coefficients if the model changes. Kept as a pure, portable SELECT (BigQuery-compatible):
-- the model's intercept/coefficients and the StandardScaler mean/std learned on the TRAIN
-- split (end_date < 2024-01-01) are baked in as literal constants, so scoring is just a
-- linear combination + a manual sigmoid (1/(1+EXP(-logit))) -- no ML runtime needed in SQL.
--
-- Encoding (must match churn_model.py's build_features exactly):
--   *_z            = (raw - train_mean) / train_std                (4 standardized numerics)
--   plan_annual    = 1 if plan_type='annual' else 0                 (baseline: monthly)
--   is_b2b         = 1 if customer_type='B2B' else 0                (baseline: B2C; SMB+Enterprise
--                    collapsed into B2B for the model -- simplification, see results.md)
--   rc_*           = 1 if renewal_change_bucket=<label> else 0      (baseline: 'flat';
--                    dummies: contraction / expansion / no_prior_renewal)
--   gw_*           = 1 if main_gateway=<label> else 0               (baseline: Stripe, and a
--                    NULL main_gateway -- 28 of 1,024 May-24 rows, no payment posted yet on an
--                    in-progress period -- also falls to the Stripe baseline; the model never
--                    saw a "no gateway" class in training, see results.md caveat)
-- Model: class_weight='balanced' logistic regression, trained on periods with a known
-- outcome ending before 2024-01-01, tested on periods ending 2024-01-01..2024-04-30.
-- contrib_* columns are included so the CSV/Python step can label each row's single
-- largest driver in plain language without re-deriving the linear algebra.
WITH feats AS (
    SELECT
        subscription_id, user_id, segment, customer_type, plan_type, start_date, end_date,
        mrr, period_number, main_gateway, renewal_change_bucket,
        (active_days    - 14.0298749421)    / 6.0676124487    AS active_days_z,
        (courses_seen   - 6.5088003705)   / 3.5310167243   AS courses_seen_z,
        (materials_seen - 29.7880963409) / 16.3771770677 AS materials_seen_z,
        (period_number  - 3.5013895322)  / 2.3722326293  AS period_number_z,
        CASE WHEN plan_type = 'annual' THEN 1 ELSE 0 END AS plan_annual,
        CASE WHEN customer_type = 'B2B' THEN 1 ELSE 0 END AS is_b2b,
        CASE WHEN renewal_change_bucket = 'contraction'      THEN 1 ELSE 0 END AS rc_contraction,
        CASE WHEN renewal_change_bucket = 'expansion'        THEN 1 ELSE 0 END AS rc_expansion,
        CASE WHEN renewal_change_bucket = 'no_prior_renewal' THEN 1 ELSE 0 END AS rc_no_prior_renewal,
        CASE WHEN main_gateway = 'PayPal'        THEN 1 ELSE 0 END AS gw_paypal,
        CASE WHEN main_gateway = 'MercadoPago'    THEN 1 ELSE 0 END AS gw_mercadopago,
        CASE WHEN main_gateway = 'Payoneer'       THEN 1 ELSE 0 END AS gw_payoneer,
        CASE WHEN main_gateway = 'Wire Transfer'  THEN 1 ELSE 0 END AS gw_wire_transfer
    FROM mart_a1_05_may24_population
),
contribs AS (
    SELECT
        *,
        -2.0161778266    * active_days_z    AS contrib_active_days,
        -4.6493060295   * courses_seen_z   AS contrib_courses_seen,
        -7.4415981228 * materials_seen_z AS contrib_materials_seen,
        0.2148660253  * period_number_z  AS contrib_tenure,
        0.0000000000      * plan_annual      AS contrib_plan_annual,
        1.3420841008           * is_b2b           AS contrib_is_b2b,
        0.0415651094   * rc_contraction   AS contrib_rc_contraction,
        0.0350816717     * rc_expansion     AS contrib_rc_expansion,
        -0.3155878263 * rc_no_prior_renewal AS contrib_rc_no_prior_renewal,
        0.2684424858        * gw_paypal        AS contrib_gw_paypal,
        -0.0666200092   * gw_mercadopago   AS contrib_gw_mercadopago,
        -0.5759692666      * gw_payoneer      AS contrib_gw_payoneer,
        -0.0015501750 * gw_wire_transfer AS contrib_gw_wire_transfer
    FROM feats
),
scored AS (
    SELECT
        *,
        -14.0365273485
        + contrib_active_days + contrib_courses_seen + contrib_materials_seen + contrib_tenure
        + contrib_plan_annual + contrib_is_b2b
        + contrib_rc_contraction + contrib_rc_expansion + contrib_rc_no_prior_renewal
        + contrib_gw_paypal + contrib_gw_mercadopago + contrib_gw_payoneer + contrib_gw_wire_transfer
        AS logit
    FROM contribs
)
SELECT
    subscription_id, user_id, segment, customer_type, plan_type, start_date, end_date,
    mrr, period_number, main_gateway, renewal_change_bucket,
    active_days_z, courses_seen_z, materials_seen_z, period_number_z,
    plan_annual, is_b2b, rc_contraction, rc_expansion, rc_no_prior_renewal,
    gw_paypal, gw_mercadopago, gw_payoneer, gw_wire_transfer,
    contrib_active_days, contrib_courses_seen, contrib_materials_seen, contrib_tenure,
    contrib_plan_annual, contrib_is_b2b, contrib_rc_contraction, contrib_rc_expansion,
    contrib_rc_no_prior_renewal, contrib_gw_paypal, contrib_gw_mercadopago,
    contrib_gw_payoneer, contrib_gw_wire_transfer,
    logit,
    1.0 / (1.0 + EXP(-logit)) AS prob_churn,
    CASE
        WHEN 1.0 / (1.0 + EXP(-logit)) >= 0.5   THEN 'High'
        WHEN 1.0 / (1.0 + EXP(-logit)) >= 0.25 THEN 'Medium'
        ELSE 'Low'
    END AS risk_tier,
    mrr * (1.0 / (1.0 + EXP(-logit))) AS mrr_at_risk
FROM scored
ORDER BY prob_churn DESC
